name: Run Automation Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '23'

      - name: Cache Maven dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      - name: Install Allure
        run: |
          sudo apt update
          sudo apt install -y allure

      - name: Run Tests
        run: mvn clean test

      - name: Generate Allure Report
        run: mvn allure:report || true

      - name: Upload Test Results (Allure Report)
        uses: actions/upload-artifact@v3
        with:
          name: allure-report
          path: target/site/allure-maven-plugin/
          retention-days: 7

      - name: Upload Test Logs
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/
          retention-days: 7
